---
- name: Trigger Terraform Cloud Run
  hosts: localhost
  connection: local
  vars:
    tfc_token: "{{ lookup('env', 'TF_API_TOKEN') }}"
    organization: "my-org"
    workspace: "my-workspace"
  tasks:
    - name: Create a Terraform Run
      uri:
        url: "https://app.terraform.io/api/v2/runs"
        method: POST
        headers:
          Content-Type: "application/vnd.api+json"
          Authorization: "Bearer {{ tfc_token }}"
        body_format: json
        body:
          data:
            type: "runs"
            attributes:
              message: "Triggered from Ansible Tower"
              is-destroy: false
            relationships:
              workspace:
                data:
                  type: "workspaces"
                  name: "{{ workspace }}"
        status_code: 201
      register: run_response

    - name: Show Run URL
      debug:
        msg: "Terraform Run triggered: {{ run_response.json.data.attributes.status }} (ID: {{ run_response.json.data.id }})"
